
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'esinabox'

  # doesn't already exist on the user's system.
  # config.vm.box_url = 'http://domain.com/path/to/above.box'

  config.vm.network :forwarded_port, guest: 9200, host: 9200
  config.vm.network :forwarded_port, guest: 9300, host: 9300
end
